### ISSUE TITLE
Search for campaigns in the client

### ISSUE THREAD

**Issue by etorres** [criteo/criteo-java-marketing-transition-sdk#4]
Hi,

Would it be possible to have in the Java client a resource to search for campaigns, similar to the one that exists in the API?

https://developers.criteo.com/marketing-solutions/reference/campaign#searchcampaigns

Thanks!

Erik

**Comment by etorres** [comment]
Another possibility would be to add support for the Campaign and CampaignId dimensions in the AnalyticsApi. It seems that these dimensions exist in the REST API.

**Comment by ouvreboite** [comment]
Hello @etorres,

We are currently working on automating the generation of SDKs to maintain up-to-date clients. This effort won't be completed before a few months, but, in the meantime, we will manually release a new set of SDKs that will cover the 2021-10 version (and so the search-camapaigns endpoints that you mention).

This manual release should happen in the coming weeks. I'll ping you here with more details once it is done.

**Comment by etorres** [comment]
That will be great!

**Comment by ouvreboite** [comment]
Hello @etorres , just to let you know that published a first set of Java SDK for the 2021-10 version. Those new SDKs are divided by service (MarketingSolutions and RetailMedia):

- [criteo-api-marketingsolutions-sdk](https://search.maven.org/artifact/com.criteo/criteo-api-marketingsolutions-sdk)
- [criteo-api-retailmedia-sdk](https://search.maven.org/artifact/com.criteo/criteo-api-retailmedia-sdk)

For your use case, here is a sample snippet:

Import dependency:
```
<dependency>
  <groupId>com.criteo</groupId>
  <artifactId>criteo-api-marketingsolutions-sdk</artifactId>
  <version>2021.10.0.211126</version>
</dependency>
```
Code snippet:
```
public static void main(String[] args) {
      var client = Configuration.getDefaultApiClient();
      client.setUsername("clientId");
      client.setPassword("clientSecret");

      var campaignApi = new CampaignApi(client);
      var searchFilters = new CampaignSearchFilters();
      searchFilters.setCampaignIds(Arrays.asList("1","2","3"));
      var searchRequest = new CampaignSearchRequest();
      searchRequest.setFilters(searchFilters);

      try {
          var portfolio = campaignApi.searchCampaigns(searchRequest);
          System.out.println(portfolio.getData());
      } catch (ApiException e) {
          System.out.println(e.getCode());
      }
}
```

**Comment by etorres** [comment]
Thank you so much for your assistance!
